[versions]
kotlin = "1.9.20"
coroutines = "1.7.3"
serialization = "1.5.1"
compose = "1.6.0"
okio = "4.14.0"
multiplatform-settings = "1.1.0"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

